export type AnalyticsSample = {
  date: string;
  referrer: string;
  source: string;
  medium: string;
  campaign: string;
  content: string;
  term: string;
  country: string;
  device: string;
  browser: string;
  os: string;
  path: string;
  hostname: string;
  visitorId: string;
  goal: string;
  revenue: number;
  eventType: "pageview" | "goal";
  metadata?: Record<string, string | number | boolean | null>;
};

export const analyticsSamples: AnalyticsSample[] = [
  {
    date: "2026-01-16",
    referrer: "https://google.com",
    source: "google",
    medium: "cpc",
    campaign: "winter-launch",
    content: "search-ad-1",
    term: "analytics platform",
    country: "US",
    device: "desktop",
    browser: "chrome",
    os: "macos",
    path: "/",
    hostname: "app.ralph.dev",
    visitorId: "visitor-1",
    goal: "signup",
    revenue: 0,
    eventType: "pageview",
    metadata: {
      session_id: "sess-1001",
      landing_variant: "hero-a",
    },
  },
  {
    date: "2026-01-16",
    referrer: "https://google.com",
    source: "google",
    medium: "cpc",
    campaign: "winter-launch",
    content: "search-ad-1",
    term: "analytics platform",
    country: "US",
    device: "desktop",
    browser: "chrome",
    os: "macos",
    path: "/pricing",
    hostname: "app.ralph.dev",
    visitorId: "visitor-1",
    goal: "signup",
    revenue: 120,
    eventType: "goal",
    metadata: {
      signup_method: "google",
      seats: 3,
    },
  },
  {
    date: "2026-01-17",
    referrer: "https://twitter.com",
    source: "twitter",
    medium: "social",
    campaign: "launch-week",
    content: "launch-thread",
    term: "datafast",
    country: "GB",
    device: "mobile",
    browser: "safari",
    os: "ios",
    path: "/",
    hostname: "marketing.ralph.dev",
    visitorId: "visitor-2",
    goal: "",
    revenue: 0,
    eventType: "pageview",
  },
  {
    date: "2026-01-17",
    referrer: "https://twitter.com",
    source: "twitter",
    medium: "social",
    campaign: "launch-week",
    content: "launch-thread",
    term: "datafast",
    country: "GB",
    device: "mobile",
    browser: "safari",
    os: "ios",
    path: "/features",
    hostname: "marketing.ralph.dev",
    visitorId: "visitor-2",
    goal: "",
    revenue: 0,
    eventType: "pageview",
  },
  {
    date: "2026-01-18",
    referrer: "https://news.ycombinator.com",
    source: "hn",
    medium: "community",
    campaign: "show-hn",
    content: "show-hn",
    term: "analytics",
    country: "DE",
    device: "desktop",
    browser: "firefox",
    os: "linux",
    path: "/blog/launch",
    hostname: "blog.ralph.dev",
    visitorId: "visitor-3",
    goal: "demo_request",
    revenue: 0,
    eventType: "goal",
    metadata: {
      demo_type: "enterprise",
      score: 87,
    },
  },
  {
    date: "2026-01-18",
    referrer: "https://news.ycombinator.com",
    source: "hn",
    medium: "community",
    campaign: "show-hn",
    content: "show-hn",
    term: "analytics",
    country: "DE",
    device: "desktop",
    browser: "firefox",
    os: "linux",
    path: "/pricing",
    hostname: "blog.ralph.dev",
    visitorId: "visitor-3",
    goal: "",
    revenue: 0,
    eventType: "pageview",
  },
  {
    date: "2026-01-19",
    referrer: "https://newsletter.example.com",
    source: "newsletter",
    medium: "email",
    campaign: "jan-recap",
    content: "january-newsletter",
    term: "retention",
    country: "CA",
    device: "desktop",
    browser: "edge",
    os: "windows",
    path: "/",
    hostname: "app.ralph.dev",
    visitorId: "visitor-4",
    goal: "",
    revenue: 0,
    eventType: "pageview",
  },
  {
    date: "2026-01-19",
    referrer: "https://newsletter.example.com",
    source: "newsletter",
    medium: "email",
    campaign: "jan-recap",
    content: "january-newsletter",
    term: "retention",
    country: "CA",
    device: "desktop",
    browser: "edge",
    os: "windows",
    path: "/pricing",
    hostname: "app.ralph.dev",
    visitorId: "visitor-4",
    goal: "purchase",
    revenue: 240,
    eventType: "goal",
    metadata: {
      plan: "pro",
      coupon: "jan-recap",
    },
  },
];
